import styles from './Page4Explain.module.css'

function parseBold(text) {
  return text.split(/(\*\*[^*]+\*\*)/).map((p, i) =>
    p.startsWith('**') ? <strong key={i}>{p.slice(2,-2)}</strong> : p
  )
}

export default function Page4Explain({ result, onNext, onBack }) {
  const { recommendation: r } = result

  return (
    <div className={styles.page}>
      <div className={`${styles.hero} animate-in`}>
        <h2 className={styles.title}>AI Explainability</h2>
        <p className={styles.desc}>Understand why the AI made this recommendation.</p>
      </div>

      <div className={`${styles.pathwayBanner} animate-in delay-1`} style={{ background: r.color+'12', borderColor: r.color }}>
        <span className={styles.pathwayIcon}>{r.icon}</span>
        <div>
          <p className={styles.pathwayLabel}>Final Recommendation</p>
          <p className={styles.pathwayName} style={{ color: r.color }}>{r.recommendation}</p>
        </div>
        <div className={styles.confBadge} style={{ background: r.color, color:'#fff' }}>
          {Math.round(r.confidence*100)}% confidence
        </div>
      </div>

      <div className={`${styles.card} animate-in delay-2`}>
        <p className={styles.sectionTitle}>🔍 Reasoning Steps</p>
        <ol className={styles.list}>
          {r.explanation.map((point, i) => (
            <li key={i} className={styles.item}>
              <span className={styles.num}>{i+1}</span>
              <span className={styles.text}>{parseBold(point)}</span>
            </li>
          ))}
        </ol>
      </div>

      <div className={`${styles.aiNote} animate-in delay-3`}>
        <span className={styles.aiIcon}>🤖</span>
        <p>This is a recommendation generated by AI based on image analysis and food safety parameters.</p>
      </div>

      <div className={`${styles.actions} animate-in delay-4`}>
        <button className={styles.backBtn} onClick={onBack}>← Back to Result</button>
        <button className={styles.nextBtn} onClick={onNext}>View Environmental Impact →</button>
      </div>
    </div>
  )
}
